# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Taller Limpieza y transformación de datos**🧹

**IMPORTANTE**: Guarda una copia de este notebook en tu Google Drive o computador.

**Taller en grupos de 3 o parejas.**

**Nombres estudiantes:**

- David Santiago Castiblanco Bogoya
-
-

**Forma de entrega:**

- Nombrar el archivo de la siguiente forma:“Taller_Limpieza_nombres_y_appellidos.ipynb”.
- Suba el Jupyter Notebook a su cuenta en Github y envíe el link en el siguiente Forms: https://forms.office.com/r/6GZ89uiLNC.

**IMPORTANTE:** No se recibirán talleres en Google Colab, el notebook debe estar subido en Github.

**Plazo de entrega:**

19 de marzo de 2026, máximo a las 11:59 p.m. Tenga en cuenta que luego de esa hora el formulario en forms se cierra. El Jupupyter Notebook también debe quedar subido en Github antes de esa hora.

**Instrucciones Generales:**

Completa el código en las celdas marcadas con `### TU CÓDIGO AQUÍ ###`. Puedes añadir más celdas si lo requieres.

Utilice la base de la GEIH de julio a diciembre de 2025, la cual se encuentra en https://drive.google.com/drive/folders/1Th4TWdsOahAAvBUKxixFhaELC_KPsl3y?usp=sharing. Tenga en cuenta sep="," y encoding='latin1'. Las variables 'DPTO' y 'RAMA4D_R4' deben ser cargadas como string.

# Ejercicio 1: Importar librerías y cargar datos

1.	Importe todas las librerías que vaya a utilizar.

In [2]:

import pandas as pd
import numpy as np

2.	Mejore la visualización de los dataframes como se ha visto en clase.

In [3]:

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', '{:.2f}'.format)

3.	Conéctese a su Google Drive y establezca la ruta del dataset.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

4.	Cargue los datos en el notebook. Llame al dataframe 'df_geih'

In [9]:
ruta = '/content/GEIH_2025_Jul_Dic_Consolidado.csv'

df_geih = pd.read_csv(
    ruta,
    sep=',',
    encoding='latin1',
    dtype={'DPTO': str, 'RAMA4D_R4': str}
)

/tmp/ipykernel_171/1640202800.py:3: DtypeWarning: Columns (74,89,102,110,116,137,204,254,257,261,263,266,268,277,298,306) have mixed types. Specify dtype option on import or set low_memory=False.
  df_geih = pd.read_csv(

5. Obtenga las dimensiones de la base

In [10]:
df_geih.shape

(409127, 314)

In [13]:
df_geih = pd.read_csv(
    ruta,
    sep=',',
    encoding='latin1',
    dtype={'DPTO': str, 'RAMA4D_R4': str},
    low_memory=False
)

# Ejercicio 2:  Seleccionar y renombrar columnas

La GEIH contiene cientos de variables. Para nuestro análisis del mercado laboral, nos enfocaremos en un subconjunto.

Adicionalmente, los nombres de las columnas en la GEIH son códigos. Para hacer el análisis más intuitivo, vamos a renombrarlas.

1. Crea un nuevo DataFrame llamado `df_empleo` que contenga únicamente las columnas que están en la lista `columnas_interes`.

In [15]:
columnas_interes = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'MES', 'CLASE', 'DPTO', 'FEX_C18', 'PT', 'P3271', 'P6040', 'P6080', 'P3043', 'OCI',
                    'P6430', 'RAMA4D_R4', 'INGLABO', 'DESCRIPCION_CIIU', 'NOMBRE_DPTO']

In [16]:
df_empleo = df_geih[columnas_interes].copy()

2. Renombra las columnas del DataFrame `df_empleo` utilizando el diccionario `mapa_nombres`.

In [17]:
mapa_nombres = {
'DIRECTORIO': 'id_vivienda',
'SECUENCIA_P': 'id_hogar',
'ORDEN': 'id_persona',
'MES': 'mes',
'CLASE': 'clase',
'DPTO': 'departamento',
'FEX_C18': 'factor_expansion',
'PT': 'poblacion_total',
'P3271': 'sexo',
'P6040': 'edad',
'P6080': 'grupo_etnico',
'P3043': 'nivel_educativo',
'OCI': 'ocupados',
'P6430': 'categoria_ocupacional',
'RAMA4D_R4': 'cod_ciiu',
'INGLABO': 'ingreso_laboral',
'DESCRIPCION_CIIU': 'desc_ciiu',
'NOMBRE_DPTO': 'nombre_dpto'}

In [18]:
df_empleo = df_empleo.rename(columns=mapa_nombres)

3. Obtenga las dimensiones de la base

In [19]:

df_empleo.shape

(409127, 18)

# Ejercicio 3: Revisión de duplicados

Un paso crucial en la limpieza es asegurar que no haya observaciones duplicadas que puedan sesgar nuestro análisis.

1. Verifica si hay filas duplicadas en `df_empleo`.

In [20]:
df_empleo.duplicated().any()

np.False_

2. Cuenta cuántas filas duplicadas existen.

In [21]:
df_empleo.duplicated().sum()

np.int64(0)

3. Elimina las filas duplicadas, si las hay.

In [22]:
df_empleo = df_empleo.drop_duplicates()

4. Verifica si hay filas duplicadas específicamente en las columnas 'id_vivienda', 'id_hogar', 'id_persona'.

In [23]:
df_empleo.shape

(409127, 18)

# Ejercicio 4: Valores faltantes

Los datos del mundo real raramente están completos. Aquí, trataremos los valores faltantes en la columna de ingresos.

1. Calcula el número de valores nulos (`NaN`) en la columna `ingreso_laboral` **antes** de cualquier modificación.

In [24]:
df_empleo['ingreso_laboral'].isna().sum()

np.int64(231144)

2. En la GEIH, un ingreso faltante a menudo significa que la persona no reportó ingresos o no aplica (ej. no trabaja). Una estrategia común es imputar estos valores con `0`. Rellena los valores `NaN` en la columna `ingreso_laboral` con `0`.

In [25]:
df_empleo['ingreso_laboral'] = df_empleo['ingreso_laboral'].fillna(0)

# Ejercicio 5: Decodificar variables

Las variables categóricas a menudo necesitan ser "traducidas" para hacerlas más entendibles para el análisis.

1. Usa los siguientes diccionarios para reemplazar los códigos numéricos por etiquetas de texto en las siguientes columnas: 'clase', 'sexo', 'grupo_etnico', 'nivel_educativo' y 'categoria_ocupacional'. Muestra los conteos de las nuevas categorías usando `.value_counts()` para verificar el cambio en cada una de las columnas.

In [26]:
dic_clase = {1: 'Cabeceras', 2: 'Centros poblados y rural disperso'}
dic_sexo = {1: 'Hombre', 2: 'Mujer'}
dic_etnico = {1: 'Indígena', 2: 'Gitano (Rom)', 3: 'Raizal del archipiélago', 4: 'Palenquero',
              5: 'Negro, mulato (afrodescendiente)', 6: 'Ninguno de los anteriores'}
dic_nivel_educativo = {1: 'Ninguno', 2: 'Educación media', 3: 'Educación media',
                       4: 'Educación media', 5: 'Técnica profesional', 6: 'Tecnológica',
                       7: 'Universitaria', 8: 'Especialización', 9: 'Maestría',
                       10: 'Doctorado', 99: 'No sabe, no informa'}
dic_cat_ocu = {1: 'Asalariado', 2: 'Asalariado', 3: 'Asalariado',
               8: 'Asalariado', 4: 'Independiente', 5: 'Independiente',
               9: 'Independiente', 6: 'Trabajador sin remuneración',
               7: 'Trabajador sin remuneración'}

In [27]:
df_empleo['clase'] = df_empleo['clase'].replace(dic_clase)
df_empleo['clase'].value_counts()

clase
Cabeceras                            356377
Centros poblados y rural disperso     52750
Name: count, dtype: int64

In [28]:
df_empleo['sexo'] = df_empleo['sexo'].replace(dic_sexo)
df_empleo['sexo'].value_counts()

sexo
Mujer     218597
Hombre    190530
Name: count, dtype: int64

In [29]:
df_empleo['grupo_etnico'] = df_empleo['grupo_etnico'].replace(dic_etnico)
df_empleo['grupo_etnico'].value_counts()

grupo_etnico
Ninguno de los anteriores           350562
Negro, mulato (afrodescendiente)     39032
Indígena                             18420
Raizal del archipiélago                925
Palenquero                             120
Gitano (Rom)                            68
Name: count, dtype: int64

In [30]:
df_empleo['nivel_educativo'] = df_empleo['nivel_educativo'].replace(dic_nivel_educativo)
df_empleo['nivel_educativo'].value_counts()

nivel_educativo
Educación media        116635
Universitaria           32517
Técnica profesional     24503
Ninguno                 12963
Tecnológica             10640
Especialización          7927
Maestría                 3154
Doctorado                 339
No sabe, no informa         1
Name: count, dtype: int64

In [31]:
df_empleo['categoria_ocupacional'] = df_empleo['categoria_ocupacional'].replace(dic_cat_ocu)
df_empleo['categoria_ocupacional'].value_counts()

categoria_ocupacional
Asalariado                     92016
Independiente                  82498
Trabajador sin remuneración     7339
Name: count, dtype: int64

# Ejercicio 6: Reorganizar columnas

1. Reorganiza las columnas con el siguiente orden: 'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto',     'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral'

In [32]:
nuevo_orden = [
    'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase',
    'departamento', 'nombre_dpto', 'factor_expansion', 'poblacion_total',
    'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados',
    'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral'
]

df_empleo = df_empleo[nuevo_orden]

# Ejercicio 7: Cambiar tipo de dato

Para realizar cálculos y análisis correctamente, las columnas deben tener el tipo de dato adecuado (numérico, categórico, etc.).

1.  Muestra en pantalla los tipos de datos actuales de `df_empleo`.

In [33]:
df_empleo.dtypes

id_vivienda                int64
id_hogar                   int64
id_persona                 int64
mes                        int64
clase                     object
departamento              object
nombre_dpto               object
factor_expansion         float64
poblacion_total            int64
sexo                      object
edad                       int64
grupo_etnico              object
nivel_educativo           object
ocupados                 float64
categoria_ocupacional     object
cod_ciiu                  object
desc_ciiu                 object
ingreso_laboral          float64
dtype: object

2.  Las siguientes columnas representan categorías: 'clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico', 'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu'. Conviértelas al tipo `category` para optimizar el uso de memoria y facilitar análisis futuros.

In [34]:
columnas_categoria = [
    'clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico',
    'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu'
]

df_empleo[columnas_categoria] = df_empleo[columnas_categoria].astype('category')

# Ejercicio 8: Ordenar el dataframe (5%)

1. Ordena el dataframe por la columna "edad" de mayor a menor. Observa la columna 'edad' y escribe en una celda de markdown cuál fue la edad mínima y la edad máxima de las personas que respondieron la encuesta de la GEIH.

In [35]:
df_empleo = df_empleo.sort_values(by='edad', ascending=False)
df_empleo[['edad']].head()

        edad
256896   108
5135     108
32904    106
256662   106
396633   106

Escribe tu análisis aquí:La edad mínima reportada en la base es **X** años y la edad máxima es*Y años.

# Ejercicio 9: Groupby

Agrupar los datos por categorías, nos permite realizar análisis más profundos y obtener insights valiosos, que a simple vista no vemos en la base de datos.

1. Crea un nuevo dataframe llamado "df_sexo" donde se agrupe por 'sexo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de sexo en una columna.

In [36]:
df_sexo = df_empleo.groupby('sexo')[['poblacion_total', 'ocupados']].sum()
df_sexo['porcentaje_ocupados'] = df_sexo['ocupados'] / df_sexo['poblacion_total']
df_sexo = df_sexo.reset_index()

df_sexo

/tmp/ipykernel_171/1486558223.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_sexo = df_empleo.groupby('sexo')[['poblacion_total', 'ocupados']].sum()

     sexo  poblacion_total  ocupados  porcentaje_ocupados
0  Hombre           190530 100790.00                 0.53
1   Mujer           218597  81063.00                 0.37

2. Crea un nuevo dataframe llamado "df_educacion" donde se agrupe por 'nivel_educativo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de nivel educativo en una columna.

In [37]:
df_educacion = df_empleo.groupby('nivel_educativo')[['poblacion_total', 'ocupados']].sum()
df_educacion['porcentaje_ocupados'] = df_educacion['ocupados'] / df_educacion['poblacion_total']
df_educacion = df_educacion.reset_index()

df_educacion

/tmp/ipykernel_171/591247024.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_educacion = df_empleo.groupby('nivel_educativo')[['poblacion_total', 'ocupados']].sum()

       nivel_educativo  poblacion_total  ocupados  porcentaje_ocupados
0            Doctorado              339    294.00                 0.87
1      Educación media           116635  66945.00                 0.57
2      Especialización             7927   6269.00                 0.79
3             Maestría             3154   2701.00                 0.86
4              Ninguno            12963   2539.00                 0.20
5  No sabe, no informa                1      1.00                 1.00
6          Tecnológica            10640   7928.00                 0.75
7  Técnica profesional            24503  16989.00                 0.69
8        Universitaria            32517  23461.00                 0.72

Escribe tu análisis aquí:

1.   Elemento de la lista
2.   Elemento de la lista
A partir de `df_sexo` y `df_educacion`, se puede observar cómo cambia la proporción de ocupados entre distintos grupos de la población.  
En el caso de `sexo`, se comparan hombres y mujeres según su población total y el número de ocupados.  
En `nivel_educativo`, se evidencia que la participación laboral puede variar dependiendo del nivel de formación alcanzado.  
En general, este tipo de agrupaciones permite identificar diferencias importantes en el mercado laboral y facilita comparar qué grupos presentan una mayor proporción de ocupación.

# Ejercicio 10: Filtrar datos

1. A partir de df_empleo, crea el DataFrame `df_ing` con observaciones donde `ingreso_laboral` no sea nulo y además sea mayor estrictamente al salario mínimo para 2026 (con subsidio de transporte).

In [38]:
salario_min_2026 = 1423500
aux_transporte_2026 = 200000
salario_total_2026 = salario_min_2026 + aux_transporte_2026

df_ing = df_empleo[
    (df_empleo['ingreso_laboral'].notna()) &
    (df_empleo['ingreso_laboral'] > salario_total_2026)
].copy()

2. ¿Cuántas personas tienen un salario estrictamente mayor al salario mínimo?

In [39]:
df_ing.shape[0]

58608

3. Crea el dataframe df_mujeres donde se encuentren solamente mujeres que están ubicadas en el departamento del Tolima, que son asalariadas y cuyo nivel educativo es educación media o superior.

In [40]:
niveles_validos = [
    'Educación media', 'Técnica profesional', 'Tecnológica',
    'Universitaria', 'Especialización', 'Maestría', 'Doctorado'
]

df_mujeres = df_empleo[
    (df_empleo['sexo'] == 'Mujer') &
    (df_empleo['nombre_dpto'] == 'Tolima') &
    (df_empleo['categoria_ocupacional'] == 'Asalariado') &
    (df_empleo['nivel_educativo'].isin(niveles_validos))
].copy()

4. ¿Cuáles son las dimensiones de df_mujeres?

In [41]:
df_mujeres.shape

(0, 18)

In [42]:
df_ing = df_empleo[df_empleo['ingreso_laboral'] > salario_total_2026].copy()